
CREATE USER ORAAPPUSER IDENTIFIED BY ORA_APP_2022
   DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE VIEW, CREATE SEQUENCE,
   CREATE PROCEDURE, CREATE TABLE, CREATE TRIGGER,
     CREATE TYPE, CREATE MATERIALIZED VIEW TO ORAAPPUSER;

